### ISSUE TITLE
Filter results by incident patient gender

### ISSUE THREAD

**Issue by thartsel** [akulasainath/18frepo#10]
As a user, I want the option to filter reaction results by incident patient gender so that I can narrow the scope of my results.

**Comment by ghost** [comment]
Updating issue title to indicate change from a sort functionality to filter functionality.

**Comment by ghost** [comment]
Updating user story to indicate change from a sort functionality to filter functionality.

**Comment by ghost** [comment]
Status changed from _In-Progress_ to _Testing_.

**Comment by ghost** [comment]
PO testing complete. Status changed from _Testing_ to _Done_.
