### ISSUE TITLE
Identify and finalize technologies to be implemented. 

### ISSUE THREAD

**Issue by ncrismali** [akulasainath/18frepo#22]
Identify technologies for the prototype.

**Comment by ghost** [comment]
Description updated

**Comment by skhandewale** [comment]
Eclipse LUNA 
GitHub
HTML5 
jQuery 
angularJS 
Bootstrap

**Comment by thartsel** [comment]
Full list of technologies used in the prototype can be found in this Technical Stack Description file:

https://github.com/akulasainath/18frepo/blob/master/18F%20Evidence/Technical%20Stack%20Description.docx

**Comment by thartsel** [comment]
Closing task -- all technologies have been finalized.
