### ISSUE TITLE
Identify and finalize the deployment model including necessary set-up and configurations steps.

### ISSUE THREAD

**Issue by ncrismali** [akulasainath/18frepo#23]
Set up test and production servers and any necessary tool configurations.

**Comment by ghost** [comment]
Description updated

**Comment by dfitch-ventera** [comment]
Test and Production Server instances are set up at Amazon Web Services along with Elastic Load Balancers and Auto-Scale Groups for each environment.  There are 2 servers in Test environment and 2 servers in Prod environment that are load balanced.  One server in each of the Test and Prod environments is in the us-east-1a Availabiity Zone and the other servers in Test and Prod are in the us-east-1b Availability Zone.  The servers are running Ubuntu 14.04 LTS Linux with the MEAN stack installed.  An AMI was created for the deployment and is used in the Launch Confguration of the Auto-Scale group for each environment.  Jenkins is being used for continuous integration builds of the application.

**Comment by thartsel** [comment]
For additional information regarding how we are using AWS technology:
https://github.com/akulasainath/18frepo/blob/master/18F%20Evidence/AWS%20Technology%20Description.docx

**Comment by thartsel** [comment]
Deployment from a Docker Container instructions can be found here:

https://github.com/akulasainath/18frepo/blob/master/18F%20Evidence/Deploying%20from%20a%20Docker%20Container.docx

**Comment by thartsel** [comment]
Local Deployment instructions can be found here: 

https://github.com/akulasainath/18frepo/blob/master/18F%20Evidence/Local%20Deployment%20Instructions.docx
