### ISSUE TITLE
Identify and finalize all the tools and technologies needed to allow continuous integration.

### ISSUE THREAD

**Issue by ncrismali** [akulasainath/18frepo#26]
Setup procedure for continuous integration and finalize any technologies to be used.

**Comment by ghost** [comment]
Description updated

**Comment by thartsel** [comment]
For additional information and evidence relating to Continuous Integration (Jenkins), our Automated Testing Framework  (Selenium, Maven, TestNG), and our Quality Management Platform - SonarQube:

https://github.com/akulasainath/18frepo/blob/master/18F%20Evidence/Continuous%20Integration%20and%20Automated%20Testing.docx
