### ISSUE TITLE
Invalid zero-values when adding more than one drug

### ISSUE THREAD

**Issue by sjfischr** [akulasainath/18frepo#27]
We're receiving zero-values when adding more than one drug.
Problem: I am getting a sporadic set of zero values when adding a drug—when clicking any filter, it resets it and the non-zero values are coming up. Usually has been happening on the second drug added.

Steps to reproduce the issue:
1)  Add “abilify”
2)  Add “ibuprofen”note all zeros
3)  Activate the “male” filternote the values are non-zero.

![zero-values on second drug](https://cloud.githubusercontent.com/assets/12958161/8296305/0991b18c-191d-11e5-9069-5c519290ae90.jpg)

![capture2](https://cloud.githubusercontent.com/assets/12958161/8296308/111a8a32-191d-11e5-9de9-221bb84243c3.PNG)

**Comment by ghost** [comment]
PO recreation and testing complete. Status changed from _Testing_ to _Done_.
