### ISSUE TITLE
View Reactions

### ISSUE THREAD

**Issue by thartsel** [akulasainath/18frepo#4]
**User Story**
As a person who was prescribed drugs, I want to be able to view the reactions reported to the FDA by drug reported for each of the drugs that I am taking so that I am aware of what to expect.

**Acceptance Criteria**
*List of reactions reported for each of the drugs entered are displayed in descending. order 
*Display the 10 most common reactions for the combination of drugs.
*Display a count for each incident
*If an incident report included multiple drugs, do not double count the reactions in the incident count.  (For example – if an incident included a headache for someone taking Advil and Adderall, this could count as a single headache reaction, not 2).
*Allow user to remove a drug from the results page (and counts will re-calculate).

**Comment by ghost** [comment]
**Acceptance Criteria**
-  Reactions returned are derived from all US incident reports provided to the FDA

**Comment by ghost** [comment]
Status changed from _In-Progress_ to _Testing_.

**Comment by ghost** [comment]
_Testing_ feedback (6/24): Update title of results page to be more clear about the nature of the results

**Comment by ghost** [comment]
New **Acceptance Criteria:**
- Page title: _Most Reported Adverse Drug Reactions_

**Comment by ghost** [comment]
Moving status from _Testing_ to _In Progress_ to incorporate changes

**Comment by ghost** [comment]
Story updates based on user survey feedback:
- Add a "Helpful tips" row above the results table with the following:
  - "Click on [insert bar graph icon] next to each reaction to see how often reactions are reported with a particular drug."
  - "Click on the reaction or drug name to learn more from the National Library of Medicine."

**Comment by ghost** [comment]
Status updated from _In Progress_ to _Testing_

**Comment by ghost** [comment]
**Acceptance Criteria** modified:
- Results are not filtered by location (US location filter removed)

PO testing complete. Status changed from _Testing_ to _Done_.
