### ISSUE TITLE
Link to Side Effect Details

### ISSUE THREAD

**Issue by thartsel** [akulasainath/18frepo#8]
As a user, I want to be able to see the side effect details associated to a drug that I am taking.

**Comment by ghost** [comment]
**Acceptance Criteria**
-User can select a side effect
-Details about the side effect are displayed

**Comment by ghost** [comment]
Updated **Acceptance Criteria**: 
- User can select a side effect
- Details about the side effect are displayed
- Link added next to individual side effect
  - Link directs users to MedlinePlus search results for the particular side effect: http://www.nlm.nih.gov/medlineplus/

**Update reason:** Acceptance criteria updated as a result of app demo on 6/23

**Comment by ghost** [comment]
Original **Acceptance Criteria**: 
- User can select a side effect
- Details about the side effect are displayed
- Link added next to individual side effect
  - Link directs users to MedlinePlus search results for the particular side effect: http://www.nlm.nih.gov/medlineplus/

Updated **Acceptance Criteria**: 
- User can select a side effect
- Link added next to individual side effect
  - Link directs users to MedlinePlus search results for the particular side effect: http://www.nlm.nih.gov/medlineplus/

**Update reason:** After prioritization, display of individual side effects was deemed to be a lower priority. Link will now direct users to the url above for more information about the adverse reaction.

**Comment by ghost** [comment]
PO testing complete. Status changed from _Testing_ to _Done_.
